### PR TITLE
handle unary expressions

### PR DESCRIPTION
**Pull request by lukekarrys**
Previously nodes with a type of `UnaryExpression` weren't being handled and would throw an error for an unexpected node type.

This PR handles the unary negation and unary plus operators as `ast.Value` types and assigns the values by multiplying by `1` or `-1`.

### CODE REVIEW

**Comment by lukekarrys** [comment]
Sorry for the direct ping, but @patrickkettner would you be able to review/merge/publish this? It would really help in a project I'm working on.

**Comment by patrickkettner** [comment]
unfortunately I no longer have merge access :(

@jhudson8, can you help?

**Comment by kpdecker** [comment]
@lukekarrys I'm trying to track down someone who is still in the organization who can help move this forward. Will update here. Worst case I may fork and ask you to open this PR over there and I'll make that repo the cannonical one.

**Comment by kpdecker** [comment]
I'm continuing support on this library over at https://github.com/kpdecker/ALCE. If you want to open this PR up there, I'd be glad to merge.

**Comment by lukekarrys** [comment]
Thanks @kpdecker! WIll do :smile:

**Pull request closed without merging**
